## Machine Learning Pipeline

As the class practice, the students will be required to develop a machine learning pipeline using the `Churn_Modelling_train_test.csv` dataset.

**About dataset**

This dataset is obained from [kaggle](https://www.kaggle.com/datasets/shubhammeshram579/bank-customer-churn-prediction?resource=download). It contains information on bank customers who either left the bank or continue to be a customer. The dataset includes the following attributes:

* Customer ID: A unique identifier for each customer
* Surname: The customer's surname or last name
* Credit Score: A numerical value representing the customer's credit score
* Geography: The country where the customer resides (France, Spain or Germany)
* Gender: The customer's gender (Male or Female)
* Age: The customer's age.
* Tenure: The number of years the customer has been with the bank
* Balance: The customer's account balance
* NumOfProducts: The number of bank products the customer uses (e.g., savings account, credit card)
* HasCrCard: Whether the customer has a credit card (1 = yes, 0 = no)
* IsActiveMember: Whether the customer is an active member (1 = yes, 0 = no)
* EstimatedSalary: The estimated salary of the customer
* Exited: Whether the customer has churned (1 = yes, 0 = no)

### Exploratory Data Analysis

In this section the students are required to do an EDA to understand the dataset.

In [69]:
# import packages
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score

In [70]:
# Load the dataset
df = pd.read_csv(r"C:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\session_2\model_utils\Churn_Modelling_train_test.csv")

In [71]:
# dataset analysis
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,Female,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,Male,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,Male,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,Male,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,Female,69.0,5,86038.21,3,0.0,0.0,192743.06,1

In [72]:
# review categorical variables
categorical_variables= df.select_dtypes(include=["object"]).columns.drop('Gender')
for col in categorical_variables:
    print(df[col].value_counts())

Surname
Smith          29
Yeh            25
Martin         25
Walker         24
Genovese       23
               ..
Beit            1
Onwuamaegbu     1
Edith           1
Holder          1
Macrossan       1
Name: count, Length: 2772, dtype: int64
Geography
France     4505
Spain      2250
Germany    2245
Name: count, dtype: int64

In [73]:
# review binary variables

In [74]:
# Preprocessing
df.loc[df["HasCrCard"] == 1.0, "HasCrCard"] = 1
df.loc[df["HasCrCard"] == 0.0, "HasCrCard"] = 0

In [75]:
df.loc[df["IsActiveMember"] == 1.0, 'IsActiveMember'] = 1
df.loc[df["IsActiveMember"] == 0.0, 'IsActiveMember'] = 0

In [76]:
df.loc[df["Exited"] == 1.0, "Exited"] = 1
df.loc[df["Exited"] == 0.0, "Exited"] = 0

In [77]:
df.loc[df["Gender"] == "Female", "Gender"] = 1
df.loc[df["Gender"] == "Male", "Gender"] = 0

In [78]:
#Review binary variables
binary_variables= ['HasCrCard', 'IsActiveMember', 'Exited','Gender']
for col in binary_variables:
    print(df[col].value_counts())

HasCrCard
1.0    6351
0.0    2649
Name: count, dtype: int64
IsActiveMember
1.0    4633
0.0    4368
Name: count, dtype: int64
Exited
0    7161
1    1840
Name: count, dtype: int64
Gender
0    4906
1    4095
Name: count, dtype: int64

In [79]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,1,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,0,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,0,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,0,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,1,69.0,5,86038.21,3,0.0,0.0,192743.06,1

In [80]:
numerical_variables = df.select_dtypes(include=["int64", "float64"]).columns.difference(binary_variables)
for col in numerical_variables:
    print(df[col].describe())

count    9000.000000
mean       38.901781
std        10.450760
min        18.000000
25%        32.000000
50%        37.000000
75%        44.000000
max        92.000000
Name: Age, dtype: float64
count      9001.000000
mean      76222.210827
std       62432.198151
min           0.000000
25%           0.000000
50%       96997.090000
75%      127450.140000
max      250898.090000
Name: Balance, dtype: float64
count    9001.000000
mean      650.681369
std        96.539591
min       350.000000
25%       584.000000
50%       652.000000
75%       718.000000
max       850.000000
Name: CreditScore, dtype: float64
count    9.001000e+03
mean     1.569072e+07
std      7.179353e+04
min      1.556570e+07
25%      1.562811e+07
50%      1.569096e+07
75%      1.575265e+07
max      1.581569e+07
Name: CustomerId, dtype: float64
count      9001.000000
mean     100180.823967
std       57561.189534
min          11.580000
25%       50972.600000
50%      100556.980000
75%      149458.730000
max      199992.480000
Name: EstimatedSalary, dtype: float64
count    9001.000000
mean        1.531497
std         0.579398
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         4.000000
Name: NumOfProducts, dtype: float64
count     9001.000000
mean      5003.366515
std       2884.787499
min          2.000000
25%       2509.000000
50%       4989.000000
75%       7505.000000
max      10000.000000
Name: RowNumber, dtype: float64
count    9001.000000
mean        5.007888
std         2.894025
min         0.000000
25%         2.000000
50%         5.000000
75%         7.000000
max        10.000000
Name: Tenure, dtype: float64

**EDA Conclusions**

From this Exploratory Data Analysis we can retrieve the following information:
* *To be completed by the student*

### ML Pipeline

In this section the students are required to create a ML pipeline to predict whether the customer left the bank or not.

In [81]:
# import packages
import pandas as pd

In [82]:
# Load the dataset
df = pd.read_csv(r"C:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\session_2\model_utils\Churn_Modelling_train_test.csv")

In [83]:
#Preprocessing Gender Variable
df= df.dropna()

df.loc[df["Gender"] == "Female", "Gender"] = 1
df.loc[df["Gender"] == "Male", "Gender"] = 0
df["Gender"]= df["Gender"].astype(int)
df["IsActiveMember"]= df["IsActiveMember"].astype(int)
df["HasCrCard"]= df["HasCrCard"].astype(int)

df=df.drop(columns=["RowNumber", "CustomerId", "Surname"])

In [84]:
# Preprocess the features - create a function or a class for it 
def transform(df: pd.DataFrame) -> pd.DataFrame:
    pass

In [85]:
# balance the dataset (if you think it is necessary)
def balance_dataset(df: pd.DataFrame) -> pd.DataFrame:
    # Separate the classes
    df_y0 = df[df['Exited'] == 0]
    df_y1 = df[df['Exited'] == 1]

    # Find the smaller class size
    min_size = len(df_y1)

    # Randomly sample from each class
    df_y0_balanced = df_y0.sample(n=min_size, random_state=42)

    # Concatenate back together
    df_balanced = pd.concat([df_y0_balanced, df_y1])

    # Shuffle the dataset
    df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

    return df_balanced

df = balance_dataset(df)

In [86]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,674,France,0,45.0,7,142072.02,1,1,0,37013.29,0
1,438,Spain,1,54.0,2,0.00,1,0,0,191763.07,1
2,749,Germany,0,47.0,9,110022.74,1,0,1,135655.29,1
3,724,Germany,0,34.0,6,118235.70,2,0,0,157137.23,0
4,586,France,1,46.0,0,0.00,3,0,1,131553.82,1

In [87]:
# Train a decision tree model using the `train sample`
df.loc[df["Exited"] == 1.0, "Exited"] = 1
df.loc[df["Exited"] == 0.0, "Exited"] = 0

In [88]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,674,France,0,45.0,7,142072.02,1,1,0,37013.29,0
1,438,Spain,1,54.0,2,0.00,1,0,0,191763.07,1
2,749,Germany,0,47.0,9,110022.74,1,0,1,135655.29,1
3,724,Germany,0,34.0,6,118235.70,2,0,0,157137.23,0
4,586,France,1,46.0,0,0.00,3,0,1,131553.82,1

In [89]:
df['Geography']= df['Geography'].astype(str)

encoder = OneHotEncoder(drop='first', sparse_output=False).set_output(transform="pandas")
encoder.fit(df[['Geography']])
encoded_df = encoder.transform(df[['Geography']])

df= pd.concat([df, encoded_df], axis=1).drop(columns=['Geography'])

In [90]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,674,0,45.0,7,142072.02,1,1,0,37013.29,0,0.0,0.0
1,438,1,54.0,2,0.00,1,0,0,191763.07,1,0.0,1.0
2,749,0,47.0,9,110022.74,1,0,1,135655.29,1,1.0,0.0
3,724,0,34.0,6,118235.70,2,0,0,157137.23,0,1.0,0.0
4,586,1,46.0,0,0.00,3,0,1,131553.82,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3675,592,1,34.0,9,0.00,2,1,1,20460.20,0,0.0,0.0
3676,608,0,33.0,1,102772.67,2,1,0,70705.58,0,1.0,0.0
3677,476,1,40.0,4,0.00,2,0,0,182547.04,0,0.0,0.0
3678,453,0,29.0,6,0.00,1,0,0,198376.02,1,0.0,0.0
3679,467,0,28.0,10,126315.26,1,1,0,32349.29,1,1.0,0.0

In [91]:
#Train and Evaluate the Model

X= df.drop('Exited', axis=1)
y= df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
# Define the model hyperparameters
params = {
    "solver": "lbfgs",
    "max_iter": 1000,
    "multi_class": "auto",
    "random_state": 8888,
}

In [93]:
# Train the model
lr = LogisticRegression(**params)
lr.fit(X_train, y_train)

c:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, multi_class='auto', random_state=8888)

### MLFlow Integration

In this section the students are required to track the model and the parameters into MLFlow.

In [94]:
# import packages for mlfow
import mlflow
import mlflow.sklearn

Start a local Tracking server on port 8080 - it is necessary to import mlflow and open a new terminal

In [95]:
# Set our tracking server uri for logging on port 8080
mlflow.set_tracking_uri("http://127.0.0.1:8080")

Visit the MLFlow UI on `http://127.0.0.1:8080`

In [96]:
# Create a new MLflow Experiment called `Practice Experiment - {Your Name}`
mlflow.set_experiment("Practice Experiment - Marah")

<Experiment: artifact_location='mlflow-artifacts:/794133133976562063', creation_time=1779208526443, experiment_id='794133133976562063', last_update_time=1779208526443, lifecycle_stage='active', name='Practice Experiment - Marah', tags={}>

In [101]:
lr.fit(X_train, y_train)

c:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, multi_class='auto', random_state=8888)

In [102]:
# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)
    # Log the loss metric
    mlflow.log_metric("f1_score", f1_score(y_test, lr.predict(X_test)))
    # Set a tag that we can use to remind ourselves what this run was for
    # Info about tags is pending
    mlflow.set_tag("Training Info", "Logistic Regression model for bank churn prediction")
    # Infer the model signature
    signature = mlflow.models.infer_signature(X_train, lr.predict(X_train))
    # Log the model
mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="logistic_regression_model",
        signature=signature,
        input_example=X_train.head())

c:\Users\Marah\Desktop\Third Trimester\ML Operations and System Design\mlops-and-system-design-Actual\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

🏃 View run flawless-bird-513 at: http://127.0.0.1:8080/#/experiments/794133133976562063/runs/9a7a797400524f0988bacd0322fa4320
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/794133133976562063

### Keep practicing

In [ ]:
# Create a new experiment using other models or different parameters
...